# Generated by Django 6.0.1 on 2026-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='batch_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
