# Generated by Django 6.0.1 on 2026-03-11 00:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_remove_subject_teachers_subjectteacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_live_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LiveSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='livestream.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['course'], name='livestream__course__bb8a25_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['subject'], name='livestream__subject_de05ad_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['start_time'], name='livestream__start_t_a8e874_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['status'], name='livestream__status_b93651_idx'),
        ),
        migrations.AddIndex(
            model_name='livesessionattendance',
            index=models.Index(fields=['session', 'user'], name='livestream__session_7aba32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='livesessionattendance',
            unique_together={('session', 'user')},
        ),
    ]
