# Generated by Django 6.0.1 on 2026-01-27 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_verified_user_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGIN_BLOCKED_UNVERIFIED', 'Login Blocked (Unverified)'), ('VERIFY_EMAIL_SUCCESS', 'Verify Email Success'), ('VERIFY_EMAIL_FAILED', 'Verify Email Failed'), ('RESEND_VERIFICATION', 'Resend Verification Email')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
