# Generated by Django 6.0.1 on 2026-03-11 00:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('SESSION', 'Live Session')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('object_id', models.UUIDField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='activity_ac_user_id_7ea57f_idx'), models.Index(fields=['type'], name='activity_ac_type_3bce11_idx'), models.Index(fields=['due_date'], name='activity_ac_due_dat_0acc2a_idx')],
            },
        ),
    ]
