# Generated by Django 6.0.1 on 2026-03-11 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_subject_teachers_subjectteacher'),
        ('quizzes', '0002_alter_subjectteacher_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quizzes_qui_subject_2fd3dd_idx',
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['subject'], name='quizzes_qui_subject_381706_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_published'], name='quizzes_qui_is_publ_8ea5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['due_date'], name='quizzes_qui_due_dat_3b60ae_idx'),
        ),
    ]
